### ISSUE TITLE
Hey! Weird Kick Message java.lang.IllegalStateException: Object already disposed minecraft

### ISSUE THREAD

**Issue by wearenoobsuk** [Ruinscraft/Panilla#100]
This happens on panilla on the last 2 versions on my 1.17.1 server running the latest paper version,
Java 16.
![chrome_BTBohhR2h8](https://user-images.githubusercontent.com/62724418/135005966-2efc2e08-c41f-4b75-a080-1ac7a84ba9ef.png)

Cannot join my creative server at all, The only thing in the console is that section in the screenshot.

Issue goes away after removing panilla, Wasn't happening on 1.16.5 before I updated :)

Thanks!

**Comment by Outlander87** [comment]
Same issue here, paper 1.17.1 latest build and panilla bought from spigot

` lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Object already disposed`

**Comment by DextonAnderson** [comment]
Earliest I can look at this is tomorrow

**Comment by DextonAnderson** [comment]
Fixed in 1.7.3
