### ISSUE TITLE
OP / Bypass permission

### ISSUE THREAD

**Issue by x1p** [Ruinscraft/Panilla#11]
Is there a bypass permission for staff? Could find any permission other than `panilla.log.chat`

Players with -OP- permissions get kicked for trying to get stuff with NBT.

**Comment by dextonanderson** [comment]
I can add an OP and permission bypass. I was reluctant to do this at first because of the high number of permission checks Panilla would have to perform. I will make a workaround, however.

**Comment by dextonanderson** [comment]
I have added this with e2bed213feab79261c42c93386117d3619ff5b1c. A new version `1.2.2` is available for download on SpigotMC.

Make sure to either: be an OP or have the `panilla.bypass` permission.

**Comment by x1p** [comment]
Sorry, didn't want to cause you extra work. A player getting kicked, especially an OP was a bit annoying. A bypass permission is off course the finest solution. :ok_hand: 
Although the copied text gets lost, it's no big deal. It's creative, so writing the text all over again is no big deal.
The latest version works great.
