### ISSUE TITLE
Conflicts with FeatherBoard

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/Panilla#19]
For some reason or another, with Panilla 1.3.x and FeatherBoard installed, players are kicked when Panilla detects a illegitimate item

@x1p

**Comment by dextonanderson** [comment]
@x1p I am unable to replicate this issue.

What server version, Panilla version, and Featherboard version are you using?

**Comment by x1p** [comment]
Panilla 1.3.2 or 1.3.3
Paper 1.13.2 build 629
Featherboard 4.19.3

Panilla 1.3.4 solved it

**Comment by dextonanderson** [comment]
Thanks, closing.
