### ISSUE TITLE
Custom Spawn Eggs

### ISSUE THREAD

**Issue by windows-virus** [Ruinscraft/Panilla#26]
People have been making custom spawn eggs which can spawn the area of effect cloud entity which can grant effects to players or create particles.

Sometimes the effects have been made to give players illegitimate effects and sometimes kill people (like the death potion) by granting them a really high instant damage effect.

Other times, people have used the particles of these entities to create particle lag.

**Comment by dextonanderson** [comment]
> People have been making custom spawn eggs which can spawn the area of effect cloud entity which can grant effects to players or create particles.

I will fix this soon
> Sometimes the effects have been made to give players illegitimate effects and sometimes kill people (like the death potion) by granting them a really high instant damage effect.

I think this might be related to #8, otherwise it shouldn't be possible. Any nbt which causes this would be helpful

**Comment by dextonanderson** [comment]
See https://github.com/Ruinscraft/Panilla/commit/02344f8199d86189b96c059db2595d91666c9c05

It will need tweaking. I honestly dont know which tags would be deemed as "useful" to builders/roleplayers
