### ISSUE TITLE
from version 1.3.6 does not work "Prevent client-side crashes due to (non-legit) item NBT!"

### ISSUE THREAD

**Issue by sergservis** [Ruinscraft/Panilla#31]
From this version will no longer fix books in the shalker

**Comment by dextonanderson** [comment]
Hi could you describe more of what you mean? Do you get a client crash?

**Comment by sergservis** [comment]
Yes! I get a client crash. Such a crash will be fixed by Panilla version 1.3.5. Version 1.3.6 client failure does not fix.

**Comment by sergservis** [comment]
![куні](https://user-images.githubusercontent.com/33991099/67987892-3723ba80-fc37-11e9-96a5-700b17857d1b.jpg)
![куені](https://user-images.githubusercontent.com/33991099/67987893-3723ba80-fc37-11e9-8886-7f6a73bec5a4.png)

**Comment by sergservis** [comment]
because of such books, such a failure occurs in the shalker

**Comment by dextonanderson** [comment]
I will have an update `1.4.2` soon that I would like you to try. I will post here when it is available.

**Comment by sergservis** [comment]
I look forward to

**Comment by windows-virus** [comment]
Filling a chest with shulker boxes with books which contain simple text can also crash players.

**Comment by sergservis** [comment]
When to wait for update 1.4.2?

**Comment by dextonanderson** [comment]
Apologies, I have final exams this week. I will get to it soon.

**Comment by dextonanderson** [comment]
Try `1.4.2` now and see if it works for you

**Comment by sergservis** [comment]
The new version did not fix the existing problem. I give you the file and nickname of the player for testing

**Comment by sergservis** [comment]
The new version did not fix the existing problem. I give you the file and nickname of the player for testing. Nick - oleg165
https://dropmefiles.com.ua/d/HhGCXSTB/398fe2ec0161a64eb0ce33ece464fc06/deff47b894e1fc757b61cee41e442318

**Comment by dextonanderson** [comment]
@sergservis Which MC server version are you using? Are you using ViaVersion?

**Comment by dextonanderson** [comment]
I was not able to reproduce a client crash on 1.13, 1.14, or 1.15

When you get the client crash, its just due to the user's inventory being full of those shulker boxes?

**Comment by sergservis** [comment]
MC 1.12.2
I use ViaVersion.

Yes, I get a crash because of them. The offending player places such on the map. Players find and open such a shalker after which they have all the equipment blocked and they can no longer log into the server.

**Comment by sergservis** [comment]
I apologize to you. I saw that it was fixed. Books in the shalkers disappeared upon re-entering the server.

**Comment by dextonanderson** [comment]
Oh, alright. I am glad it is no longer an issue for you. If it happens again, be sure to let me know!
