### ISSUE TITLE
Nobody can join after adding this plugin

### ISSUE THREAD

**Issue by cloakfox** [Ruinscraft/Panilla#36]
Panilla version: 1.4.3
Server version: PaperSpigot 1.13.2 build 652
Logs: https://pastebin.com/psbtitaC

Running behind a bungeecord with ViaVersion 2.2.1
The 1.13.2 server runs ProtocolSupport (to support 1.8 up to 1.14.4)

Server is join-able without Panilla loaded.

**Comment by dextonanderson** [comment]
Hi, could you try Panilla 1.4.1 and see if it has the same issue?

**Comment by dextonanderson** [comment]
@cloakfox Do you also happen to use Waterfall instead of BungeeCord?

**Comment by cloakfox** [comment]
Version 1.4.1 seems to be okay but can't properly test right now because nobody is online anymore.

I also use Waterfall yes.

**Comment by dextonanderson** [comment]
Alright. Good to know. I suspect 1.4.1 should work fine for you for now. I will do some testing with your particular setup and see what I can do to fix this issue.

**Comment by dextonanderson** [comment]
I wasn't able to replicate this again after testing. Is this still an issue with the latest versions of: Panilla, Waterfall, ProtocolSupport, and ViaVersion?
