### ISSUE TITLE
An error occurs when throwing a potion in large quantities

### ISSUE THREAD

**Issue by sergservis** [Ruinscraft/Panilla#41]
Spigot 1.12.2
https://pastebin.com/sUfDxEhS

**Comment by dextonanderson** [comment]
Does this happen on the latest version of Panilla? `1.4.8-fix`

**Comment by sergservis** [comment]
YES

**Comment by sergservis** [comment]
On the latest version, the exact same error

**Comment by sergservis** [comment]
https://pastebin.com/PennMpds

**Comment by dextonanderson** [comment]
Is there an easy way to replicate this with potions like you said? I briefly tried what you described with spamming a lot of potions with no luck.

**Comment by dextonanderson** [comment]
Is there an easy way to replicate this with potions like you said? I briefly tried what you described with spamming a lot of potions with no luck.

**Comment by dextonanderson** [comment]
Is there an easy way to replicate this with potions like you said? I briefly tried what you described with spamming a lot of potions with no luck.
