### ISSUE TITLE
Panilla deleting normal items in disabled worlds, not reporting it in chat

### ISSUE THREAD

**Issue by Pugabyte** [Ruinscraft/Panilla#43]
![image](https://user-images.githubusercontent.com/12417961/81871927-c72bb080-9546-11ea-9367-3b3cc36218d8.png)

[config.yml](https://paste.bnn.gg/panilla.yml)

The main thing we have noticed this with is treasure maps, however I have also heard about 5 stacks of sand and a fishing pole disappearing. 

0. I added a world to our `disabled-worlds` list, and proceeded with the following in that world.
1. Using `/locate Shipwreck`, I found a buried treasure map
2. Using `/openinv <player>` I placed it into a normal player's inventory (No panilla bypass)
3. I had the normal player drop the map; it instantly disappeared. 
    - There was no logging in console or chat that Panilla had intercepted any items. 
4. I used `/plugman unload Panilla` and repeated the process, and the map dropped on the ground.
5. I used `/plugman load Panilla` and repeated the process, and the map disappeared.
6. I restarted the server without Panilla (no other changes), and repeated the process, and the map dropped on the ground.
7. I restarted the server with Panilla (no other changes), and repeated the process, and the map disappeared. 

Throughout this whole process, players with Panilla bypass could drop the treasure map.

**Comment by dextonanderson** [comment]
I think you are reporting 2 separate issues.

1. Maps from Shipwrecks get flagged as "invalid" NBT
2. The world whitelist does not work as intended.

Is this correct?

> however I have also heard about 5 stacks of sand and a fishing pole disappearing.

This shouldn't be possible. Panilla does not remove items from inventories. Panilla only edits NBT tags.

**Comment by Pugabyte** [comment]
Three bugs, really, it should be reporting any deleted items in chat I believe? I know I've seen the message before.

The sand and fishing pole disappeared when dropping, like the maps

**Comment by dextonanderson** [comment]
> Three bugs, really, it should be reporting any deleted items in chat I believe? I know I've seen the message before.

I think I know what you mean now. It isn't reporting when a dropped item entity is removed. I will likely completely change this behavior. Entities shouldn't ultimately be removed, however stripped of NBT like items in inventories are.

**Comment by dextonanderson** [comment]
1. I have fixed the Shipwreck maps getting flagged as "invalid" NBT
2. I could not replicate the disabled-worlds issue. When I disable a world in the configuration it works fine.
3. I have changed the behavior of item entities. It will now strip the NBT from the item instead of deleting the item. It will also log when this occurs.

Check soon for a new release
