### ISSUE TITLE
crash item again...

### ISSUE THREAD

**Issue by xion87** [Ruinscraft/Panilla#44]
Hi i got a crash today i am sure the guy detected by panilla make the server crash 
logs: https://gist.github.com/xion87/b803f794891abf7cc067c2c8e71e6e59
using paperspigot 1.13.2 and panilla 1.4.8-fix (with viaversion/viarewind)

**Comment by dextonanderson** [comment]
It would help if you could send a player.dat file with the item that causes this in their inventory. It would make it exponentially easier to patch.

Thanks

**Comment by xion87** [comment]
Here :)
[4b4996f7-a3be-39f7-a3d1-96f439cd7f3b.zip](https://github.com/Ruinscraft/Panilla/files/4630591/4b4996f7-a3be-39f7-a3d1-96f439cd7f3b.zip)

**Comment by dextonanderson** [comment]
This should be fixed in the upcoming version. Check soon for a new release.
