### ISSUE TITLE
Don't flag items coming from menus

### ISSUE THREAD

**Issue by Pugabyte** [Ruinscraft/Panilla#50]
Can you add an option to ignore items coming from inventories that don't have a location (menus created by the server)?

**Comment by dextonanderson** [comment]
I think this would be a bukkit specific thing. I can look at doing this though.

**Comment by dextonanderson** [comment]
Try version 1.5.3.

Before updating, change your config to include the option `ignore-non-player-inventories: true`. You will have to add it manually.
