### ISSUE TITLE
ItemFixer

### ISSUE THREAD

**Issue by GoshaMalinov** [Ruinscraft/Panilla#52]
Can you please do it like this: https://www.spigotmc.org/resources/itemfixer-remove-creative-hacked-items-from-your-server.34250/ 

And the ability to choose enchant because I have on the project people can enchant a thing of level 10. And your plugin just deletes and I had to put " lenient"

**Comment by dextonanderson** [comment]
I would recommend the "average" strictness and whitelisting either "Enchantments" (1.13+) or "ench" (before 1.13) in the nbt-whitelist section: https://github.com/Ruinscraft/Panilla/blob/master/bukkit/src/main/resources/config.yml#L37

**Comment by GoshaMalinov** [comment]
https://sun3-12.userapi.com/9ZiS_OUDqdwTA790IQ-gqu8hlUomxBYZpGNVSg/8ZohHP7Ynro.jpg

- ench.WATER_WORKER.10
- ench.VANISHING_CURSE.10
- ench.SWEEPING_EDGE.10
- ench.SILK_TOUCH.10
- ench.RIPTIDE.10
- ench.PROTECTION_PROJECTILE.10
- ench.PROTECTION_FALL.10
Right?

Here is how to do it in the config ench.allow.MATERIAL.ENCHANTMENT.lvl - allow on the item a certain enchant.

**Comment by dextonanderson** [comment]
I will consider adding these configuration options but ultimately don't want to for a few reasons:

1. This plugin is generally designed for creative servers where limiting enchantments like this won't really matter
2. I want the configuration to be clean and simple
3. This would require a lot of integration and further implementation of higher level stuff like checking individual enchantments

Maybe consider a different plugin to limit enchantments the way you want to. I'm not sure Panilla will be the best choice for this.

**Comment by GoshaMalinov** [comment]
:(
