### ISSUE TITLE
Packets dropped when using Shopgui+

### ISSUE THREAD

**Issue by RWoof** [Ruinscraft/Panilla#56]
Shopgui+ uses items for categories etc so they have the flag enabled to hide their attributes or enchants sometimes. Is it possible to disable panilla checks on a server shop? Panilla seems to flag this and I see these errors in the console every time a Shopgui+ page is loaded (censored the player name):

```
[Panilla] Packet of type PacketPlayOutWindowItems to player (censored player name) was dropped because NBT tag HideFlags failed checks
[Panilla] Packet of type PacketPlayOutSetSlot to player (censored player name) was dropped because NBT tag HideFlags failed checks
```
I'm using this config: https://www.mc-market.org/resources/15413/ 

I think it's because some shops or items use flags to hide certain data, he's one example of the flags (not all possible flags):

```
      flags:
        - HIDE_ATTRIBUTES
        - HIDE_POTION_EFFECTS 
```

**Comment by RWoof** [comment]
Might be something similar to #50

**Comment by dextonanderson** [comment]
Try version 1.5.3.

Before updating, change your config to include the option `ignore-non-player-inventories: true`. You will have to add it manually.

**Comment by RWoof** [comment]
Thank you for the quick update! This seems to work for me!
