### ISSUE TITLE
Hello i have problem with your plugin and plugin space

### ISSUE THREAD

**Issue by Darko1green1LOrd** [Ruinscraft/Panilla#57]
im tryyng to make space Vision controller  and even tho im op and i have all bypasses for panilla it still removes the item with message 
(User Censored) was dropped because NBT tag display failed checks

and i just rename it to §3Controller its fine with §4Controller or any other color but §3Controller is for some reason flagged by it
and also the world im in is in whitelist so it shoudnt be flagging anythyng in that world

**Comment by dextonanderson** [comment]
I cannot replicate this. Is there additional lore on the item?

**Comment by dextonanderson** [comment]
You say this is another plugin which is causing the problem. Could you provide a link to it?

**Comment by dextonanderson** [comment]
Hi,

I believe the latest release, 1.5.4, will solve this problem
