### ISSUE TITLE
Entities don't respect the disabled-worlds configuration option

### ISSUE THREAD

**Issue by RWoof** [Ruinscraft/Panilla#59]
Here is the relevant section of my config:

disabled-worlds:
  - hello new world im dino girl
  - Creative2
  - hello new world im dino girl_nether
  - Creative2_nether
  - hello new world im dino girl_the_end
  - Creative2_the_end

My 7 year old named her world lol. For some reason I can't get this to work, I'm thinking it's because of the spaces in the world names? I've tried quotes around the world names, underscores instead of spaces, both, none, nothing seems to work. The names are identical to the world folders, including the capitalization. Every vindicator that drops a banner, when I pick it up, it wipes the NBT tags. Please help :)

**Comment by dextonanderson** [comment]
Try putting your worlds in single quotations.

Like: `'this is a test world with spaces'`

```
disabled-worlds:
  - 'this is a test world with spaces'
  - 'this is another world'
```

**Comment by RWoof** [comment]
Thanks, I'll give it a try, sorry I've been bothering you today!

**Comment by RWoof** [comment]
This unfortunately did not work for me either. Here's the config and a photo of my world folders:

disabled-worlds:
  - 'hello new world im dino girl'
  - 'Creative2'
  - 'hello new world im dino girl_nether'
  - 'Creative2_nether'
  - 'hello new world im dino girl_the_end'
  - 'Creative2_the_end'

![Worlds](https://user-images.githubusercontent.com/25894191/87236616-a2b64e00-c3a8-11ea-848d-bf51118f09a1.png)

**Comment by RWoof** [comment]
Unfortunately there doesn't seem to be any error message when panilla starts, I just can't get the banners to pick up with tags even if the world is apparently disabled (I'm not sure how to check if it's disabled or not in the game). 

I can see the banner drop as normal, panilla erases the tags on pickup because the NBT is hidden. Perhaps even lenient mode does this? If I whitelist hidden NBT then it'll probably allow that in all my worlds including creative which would be a mistake I think.

**Comment by dextonanderson** [comment]
Which version of MC is your server?

**Comment by RWoof** [comment]
Running Minecraft 1.16.1 using paper 88.

**Comment by dextonanderson** [comment]
Just posted a release `1.5.5` that should fix this issue

**Comment by RWoof** [comment]
It works! Thanks for the quick repair :)
