### ISSUE TITLE
Feature request: Disable update check

### ISSUE THREAD

**Issue by SlimeDog** [Ruinscraft/Panilla#62]
Feature request:
- Configuration to disable update checker. We have our own out-of-band automagical update checker.

**Comment by dextonanderson** [comment]
There is no update checker in Panilla.

**Comment by SlimeDog** [comment]
What is the reason to reach out to `api.spigotmc.org` ?

**Comment by dextonanderson** [comment]
Panilla does not reach out to `api.spigotmc.org`

Have you downloaded your version from spigotmc.org or compiled it yourself?

**Comment by dextonanderson** [comment]
Here is the file referenced in that paste.

https://github.com/Ruinscraft/Panilla/blob/master/bukkit/src/main/java/com/ruinscraft/panilla/bukkit/PanillaPlugin.java

**Comment by SlimeDog** [comment]
Downloaded fro SpigotMC.

**Comment by dextonanderson** [comment]
I am not sure what software you use to detect outgoing HTTP connections but Panilla certainly isn't making a connection to `api.spigotmc.org`. Perhaps this is some type of false positive?

Here's the decompiled PanillaPlugin file from the downloaded binary on SpigotMC
https://paste.ubuntu.com/p/9HZKyX2y62/

I encourage you to decompile it yourself. I am very much against auto updaters and making unnecessary HTTP connections.

**Comment by SlimeDog** [comment]
Agreed. So I don't understand why JavaPluginLoader is making that call, if Panilla doesn't request it. In any event, we block it. But just trying to understand, and eliminate the tracking report, if possible.

**Comment by SlimeDog** [comment]
The report is from [NetworkInterceptor](https://www.spigotmc.org/resources/networkinterceptor.53351/).

**Comment by dextonanderson** [comment]
Have you tested with and without Panilla? Any difference?

**Comment by SlimeDog** [comment]
Will do. I see that many other plugins are making similar calls. Perhaps I should address it with Luck. :(

**Comment by dextonanderson** [comment]
Also, is this a recent phenomenon? When did you start using NetworkInterceptor and when did this start flagging Panilla?

**Comment by SlimeDog** [comment]
Just started, so new to me.

**Comment by dextonanderson** [comment]
Perhaps try a test server with only NetworkInterceptor and Panilla. You can verify for yourself it isn't Panilla making the HTTP request. I do think this is strange.

**Comment by SlimeDog** [comment]
Agreed. I started using NetworkInterceptor after our network report of these outbound calls.

**Comment by dextonanderson** [comment]
This has been on the Panilla resource page ever since I posted it, haha

![](https://i.imgur.com/NJoJBTl.png)

**Comment by SlimeDog** [comment]
Thanks for the fast response. We'll also try to have a look at JavaPluginLoader. The issue may lie there.

**Comment by SlimeDog** [comment]
Explanation from my dev: For premium plugins, Spigot injects a very simple "anti-piracy" feature (the `loadConfig0` method) that generates a nonce number for each purchase of a premium resource. Then the method calls the Spigot API to make sure the user who bought the plugin (or rather the nonce generated) has access to it.

 But since I block the calls, and still use the plugins (which I have purchased), the security protection is zero.

Further explanation from my dev: The way it's set up is that if the call fails, it'll let you play anyway.
This is because of the premium resource guidelines, which state that the plugin must work without an internet connection.

**Comment by dextonanderson** [comment]
Ah yes, I forgot about that anti-piracy feature. Thanks for the explanation.
