### ISSUE TITLE
Panilla crash (1.8 Netty waitForFuture issue)

### ISSUE THREAD

**Issue by J4im3x0** [Ruinscraft/Panilla#63]
Panilla version: 1.5.6
Server version: tacospigot 1.8.8

Panilla makes the server crash https://pastebin.com/sWbGT4fv
of course I tried removing the plugin and the problem was solved

**Comment by dextonanderson** [comment]
Hi,

Seems as this only affects 1.8; I don't have many 1.8 users so that's how this slipped through the cracks.

Will have a fix out shortly

**Comment by dextonanderson** [comment]
Think you could try this build of Panilla? Includes the most recent commit I just pushed which should fix the issue. I am unable to test it, so would be grateful if you could. (.jar file is inside the .zip)
[Panilla-1.8fix.zip](https://github.com/Ruinscraft/Panilla/files/5087509/Panilla-1.8fix.zip)

**Comment by dextonanderson** [comment]
(Continued from another discussion) Please try this Panilla build:
[Panilla-1.8fix2.zip](https://github.com/Ruinscraft/Panilla/files/5087972/Panilla-1.8fix2.zip)

**Comment by dextonanderson** [comment]
(Continued from another discussion) Please try this Panilla build:
[Panilla-1.8fix3.zip](https://github.com/Ruinscraft/Panilla/files/5088024/Panilla-1.8fix3.zip)

**Comment by dextonanderson** [comment]
(Continued from another discussion) Please try this Panilla build:
[Panilla-1.8fix4.zip](https://github.com/Ruinscraft/Panilla/files/5090972/Panilla-1.8fix4.zip)

**Comment by dextonanderson** [comment]
Resolved

**Comment by dextonanderson** [comment]
(Continued from another discussion) Please try this Panilla build:
[panilla-1.8fix5.zip](https://github.com/Ruinscraft/Panilla/files/5126866/panilla-1.8fix5.zip)

**Comment by dextonanderson** [comment]
(Continued from another discussion) Please try this Panilla build:
[panilla-1.8fix6.zip](https://github.com/Ruinscraft/Panilla/files/5145427/panilla-1.8fix6.zip)
