### ISSUE TITLE
Armor stand name length check

### ISSUE THREAD

**Issue by x1p** [Ruinscraft/Panilla#66]
I had someone on the creative server that had armor stands. They had a glowing effect and very long custom names like: "wwwwwwwwwww" but then 100 times longer, you prob. get the idea.
A few of these armor stands were lagging the hell out of the clients around it. FPS more like 0 than 1.
I couldn't get a hold of one of these as an example. There is no way he could have made this using the tools/commands present.

Is this solvable or is there something that I could have done better?

strictness: average
Plugin version 1.5.9

**Comment by dextonanderson** [comment]
I can look into it. Could be a simple fix if it's just long display names of armor stands. It could be something I overlooked.

**Comment by dextonanderson** [comment]
Still an issue, will get to it soon

**Comment by dextonanderson** [comment]
Should be fixed with 1.7.1
