### ISSUE TITLE
Allow invisible item frames

### ISSUE THREAD

**Issue by Pugabyte** [Ruinscraft/Panilla#70]
I have the [Invis Item Frames plugin](https://www.spigotmc.org/resources/80692) but Panilla deletes them. Can this be changed (maybe config setting)?

**Comment by dextonanderson** [comment]
Hi,

Are you using `strictness: strict` in your config.yml?

**Comment by Pugabyte** [comment]
Our strictness level is set to `average`

**Comment by dextonanderson** [comment]
As a temporary solution, add "EntityTag" to the nbt-whitelist section of the Panilla config.yml
