### ISSUE TITLE
NBT of an item entity was stripped because NBT tag Unbreakable failed checks

### ISSUE THREAD

**Issue by Teenkung123** [Ruinscraft/Panilla#71]
when i drop any items that have unbreakable it always say and when i pickup ALL nbt of items are gone
"NBT of an item entity was stripped because NBT tag Unbreakable failed checks"
and in console it show nothing
how do i fix it?

**Comment by dextonanderson** [comment]
Hi,

You can add "Unbreakable" to the nbt-whitelist section of the Panilla config.yml

For example:
nbt-whitelist:
  - Unbreakable

**Comment by Teenkung123** [comment]
okay thx fixed now
