### ISSUE TITLE
Conflict with Build Battle Plugin

### ISSUE THREAD

**Issue by TheMattVid** [Ruinscraft/Panilla#74]
I am using this plugin on a creative plots server, and I also am running a Build Battle minigame on the same server. Whenever a Build Battle game starts, sometimes a player gets kicked with a message saying.

Internal Exception: java.lang.NullPointerException

There were no other errors, but when I ran the server in debug mode, I saw this:
https://mclo.gs/mc8Wk7j

The error mentions Panilla a few times, so I think there may be a conflict of some sort.

Edit: To be clear, this occurs right at the beginning of the Build Battle game when players get teleported to their build plots and their current inventories get saved and replaced with an empty one just for the minigame.

**Comment by dextonanderson** [comment]
This prerelease should solve your issue. I will be making a new release on SpigotMC
[Panilla_1.6.5-pre1.zip](https://github.com/Ruinscraft/Panilla/files/6057348/Panilla_1.6.5-pre1.zip)
 soon
