### ISSUE TITLE
org.bukkit:craftbukkit:1.12.2-R0.1-SNAPSHOT not found

### ISSUE THREAD

**Issue by alleggs123** [Ruinscraft/Panilla#77]
im building with gradle in cmd and im not smart what is this lmao
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':panilla-craftbukkit-v1_12_R1:compileJava'.
> Could not resolve all files for configuration ':panilla-craftbukkit-v1_12_R1:compileClasspath'.
   > Could not find org.bukkit:craftbukkit:1.12.2-R0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/no/.m2/repository/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/no/.m2/repository/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/craftbukkit-1.12.2-R0.1-SNAPSHOT.pom
       - file:/C:/Users/no/.m2/repository/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/craftbukkit-1.12.2-R0.1-SNAPSHOT.jar
       - https://jcenter.bintray.com/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/craftbukkit-1.12.2-R0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/craftbukkit-1.12.2-R0.1-SNAPSHOT.jar
     Required by:
         project :panilla-craftbukkit-v1_12_R1

**Comment by dextonanderson** [comment]
Hi,

You should compile both CraftBukkit 1.12 and CraftBukkit 1.12.2 with BuildTools before compiling Panilla.

**Comment by alleggs123** [comment]
wow thanks for responding fast, my friend is too poor to buy it so he asked me to compile the source and all i know how to do is run gradle compileJava

**Comment by alleggs123** [comment]
turns out im still trying and im putting it in intellij rn so its "easier" but my brain is being confused rn could u help kek

**Comment by dextonanderson** [comment]
Yes,

You have to compile every version of CraftBukkit/Spigot Panilla is compatible with. You do this with BuildTools. https://www.spigotmc.org/wiki/buildtools/

From the README:
```
In order for you to compile Panilla, you will need to use BuildTools, by SpigotMC, and build each version of CraftBukkit which is supported by Panilla. When you run BuildTools, it will add the dependencies required (CraftBukkit/Bukkit) to your local Maven repository. From there, you can compile the project with ./gradlew build. The output plugin jars file will located in the target/ directory.
```

Eg:
```
java -jar BuildTools.jar --rev 1.8.8
java -jar BuildTools.jar --rev 1.12
java -jar BuildTools.jar --rev 1.12.2
java -jar BuildTools.jar --rev 1.13.2
java -jar BuildTools.jar --rev 1.14.4
java -jar BuildTools.jar --rev 1.15.2
java -jar BuildTools.jar --rev 1.16
java -jar BuildTools.jar --rev 1.16.5
```
This process will take quite a long time depending on your computer and internet speed.
