### ISSUE TITLE
The problem with the Enchantment white list

### ISSUE THREAD

**Issue by botinok224** [Ruinscraft/Panilla#80]
I added protection_fall and feather_falling to the white list of enchantments and set them to a maximum enchantment limit of 10, but the game is still at level 4 of the weightlessness enchantment (boot) it subsides. This is the only enchantment I'm having trouble with with the maximum enchantment level. How do I fix this?

**Comment by botinok224** [comment]
?

**Comment by dextonanderson** [comment]
> This is the only enchantment I'm having trouble with with the maximum enchantment level. How do I fix this?

Which enchantment? You listed 2

**Comment by botinok224** [comment]
feather_falling
https://www.digminecraft.com/lists/enchantment_list_pc.php
but specifically, the limit of this enchantment does not work. Maybe it is called something else for the plugin code?

**Comment by dextonanderson** [comment]
I just put out a release on SpigotMC, 1.6.5. I believe it should address your issue

**Comment by botinok224** [comment]
thx
