### ISSUE TITLE
Packet Error

### ISSUE THREAD

**Issue by nikitushu2** [Ruinscraft/Panilla#81]
When I type anything into chat, the error arises: [
https://pastebin.com/GjjsYtgA](https://pastebin.com/GjjsYtgA)

When Panilla is disabled, the error does not arise anymore

**Comment by dextonanderson** [comment]
Hi,

Please try this prerelease version of Panilla. Let me know if it solves your issue
[Panilla_1.6.5-pre1.zip](https://github.com/Ruinscraft/Panilla/files/6252920/Panilla_1.6.5-pre1.zip)
