### ISSUE TITLE
Player skull owners getting stripped

### ISSUE THREAD

**Issue by haloflooder** [Ruinscraft/Panilla#85]
After updating to the latest version from an older version we had running. A lot of player's skulls in their chests got stripped of the skull owner from the nbt just out of nowhere.

![screenshot](https://i.imgur.com/3fauTSs.png)

We were able to fix this quickly by adding SkullOwner to the nbt whitelist. But didn't think player heads from a widely used plugin "HeadDatabase" would get wiped like this. Wish we got a warning about this in the changelogs because didn't think this would happen from "Validate UUIDs on player heads (can prevent server/client crashes)"

**Comment by dextonanderson** [comment]
I had fixed this in a later commit but haven't published a release on Spigot. Here's the updated version:
[Panilla-1.7.0.zip](https://github.com/Ruinscraft/Panilla/files/6642440/Panilla-1.7.0.zip)
