### ISSUE TITLE
Can't join on 1.17.1 with Panilla installed

### ISSUE THREAD

**Issue by Malachiel87** [Ruinscraft/Panilla#87]
When i try to join the server with 1.17.1 installed i will get kicked  with this error
Internal Exception: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.util.List (java.lang.Integer and java.util.List are in module java.base of loader 'bootstrap')

**Comment by dextonanderson** [comment]
Fixed with the latest commit. I pushed an update on SpigotMC
