### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by BratishkaErik** [Ruinscraft/Panilla#92]
BratishkaErik lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 11 bytes extra whilst reading packet 0

**Comment by strahil211** [comment]
Having the same issue! Running Airplane.jar 1.17.1 
Am able to connect without the plugin, tried very config setting and still can't connect with Panilla installed

[15:40:16 INFO]: Strahil211 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Object already disposed

**Comment by dextonanderson** [comment]
I don't seem to have this issue on Paper 1.17.1

I think this is an issue with one of the various forks of Paper

**Comment by strahil211** [comment]
Me and BratishkaErik both have CMI, could it be something related to that? He's on PaperMC and having the issue so I'm not convinced it's the server type causing it

**Comment by dextonanderson** [comment]
Seems like it's an issue with Tuinity specifically. They've added some patch which causes this issue. I tried it and was able to reproduce it.

**Comment by strahil211** [comment]
You are correct actually, it is Tuinity causing it. Should I report it to them or will you? 
I really want to use this plugin on Tuinity/Airplane

**Comment by strahil211** [comment]
I tried messing with Tuinity.yml but nothing helped that I tried. I think its packet rate related but I don't know much

**Comment by dextonanderson** [comment]
I'm going to have a look to see what it is specifically. If's something I think Tuinity should address, I'll let them know. Otherwise, I'll adapt the plugin to overcome the issue.

**Comment by dextonanderson** [comment]
FYI this commit is the culprit https://github.com/Tuinity/Tuinity/commit/5620c5720691a99ff0761093c1dab66833ecad15

**Comment by dextonanderson** [comment]
The issue basically boils down to my replacement packet decompressor for MC.

This feature is honestly kind of redundant in newer server versions which derive from Paper. They include way more security checks now than they did in previous MC versions to make sure packets aren't doing spooky things (being over/undersized etc). I've removed it and attached a compiled Panilla .jar without it. This will work for Tuinity/etc.

[panilla-nopacketdecompress.zip](https://github.com/Ruinscraft/Panilla/files/6946742/panilla-nopacketdecompress.zip)

**Comment by strahil211** [comment]
God bless you sir you are a god, I'm glad I found your plugin and purchased it. I will be using it on my new creative server and it will be much needed
Good review coming
Cheers!

**Comment by BratishkaErik** [comment]
But I am using **PaperSpigot** 1.12.2

**Comment by dextonanderson** [comment]
> But I am using PaperSpigot 1.12.2

I believe then the issue we are referencing is different from yours. Does the version I uploaded here fix your issue?

**Comment by BratishkaErik** [comment]
> > But I am using PaperSpigot 1.12.2
> 
> I believe then the issue we are referencing is different from yours. Does the version I uploaded here fix your issue?

I will check now

**Comment by BratishkaErik** [comment]
> > But I am using PaperSpigot 1.12.2
> 
> I believe then the issue we are referencing is different from yours. Does the version I uploaded here fix your issue?

I've tested with three levels of sctrictness, and so far so good, but you need to wait a bit, I'll test with a few players

**Comment by BratishkaErik** [comment]
> > > But I am using PaperSpigot 1.12.2
> > 
> > 
> > I believe then the issue we are referencing is different from yours. Does the version I uploaded here fix your issue?
> 
> I've tested with three levels of sctrictness, and so far so good, but you need to wait a bit, I'll test with a few players
The problem is gone. Thank you very much!
