### ISSUE TITLE
Latest version of Paper Build #233 unable to join the server

### ISSUE THREAD

**Issue by PancakeCatsss** [Ruinscraft/Panilla#97]
After Paper merged with Tuinity you can no longer join the server, thought it was ProtocolLib at first as that is also mentioned in the error but after updating that to the latest dev build and still having the error we disabled Panilla and can join the server.

Error: https://www.pastelog.us/utehikuvut.yaml

Line 19 for the Panilla part

**Comment by DextonAnderson** [comment]
Use this build https://github.com/Ruinscraft/Panilla/issues/92#issuecomment-894368057

**Comment by PancakeCatsss** [comment]
Works perfectly, thank you.
