### ISSUE TITLE
players sometimes cant join on paper 1.17.1

### ISSUE THREAD

**Issue by ScuroK** [Ruinscraft/Panilla#99]
on the latest paper version there seems to be an issue. players are unable to join.
i have removed panilla and that seems to fix it. on spigot this problem did not show up.

can you please check this out?
https://github.com/PaperMC/Paper/issues/6546

**Comment by ScuroK** [comment]
i did some more testing and im 100% sure its because of panilla. can you make it work on latest paper version?

**Comment by DextonAnderson** [comment]
Use this version https://github.com/Ruinscraft/Panilla/issues/92#issuecomment-894368057

**Comment by ScuroK** [comment]
Is that better than the latest version on spigot??

**Comment by DextonAnderson** [comment]
> Is that better than the latest version on spigot??

Yes, it fixes this specific issue.

**Comment by ScuroK** [comment]
Ok thx alot! Would you mind actually releasing it on spigot for the other users?

**Comment by DextonAnderson** [comment]
> Ok thx alot! Would you mind actually releasing it on spigot for the other users?

Yes, I will make a release on Spigot. I've just been holding off for a bit. Been working on some other refactoring of the project to be more easily updatable to newer version of the game.

**Comment by ScuroK** [comment]
it seems like the problem still remains sometimes. often it works for like 1 day than happens again.

**Comment by ScuroK** [comment]
[2021-09-17-4.log](https://github.com/Ruinscraft/Panilla/files/7187423/2021-09-17-4.log)
